#!/bin/bash
co="echo 'conf'"
v="echo 'interface vl 1'"
x="echo 'exit'"
#routeway="echo 'show ip route'"
#route="echo 'sho ip interface'"
routeway="echo 'ip default-gateway 172.16.1.3'"
route="echo 'ip route 172.16.0.0 255.255.0.0 172.16.1.3'"
nom=61

echo 'Cisco IP from 61 to 86'
#diap=(1	6	73	74 78	79	80	82	83	84	85	86)
diap=(83	84	85	86)
for b in ${diap[@]}; do
  a="-tt admin@172.16.1.$b"
  # Подключиться, добавить IP из другой маски, добавить маршруты
  { sleep 2 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $routeway ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.10.1.$nom 255.255.0.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a
  if (( nom != 64 )) ; then
    nom=$((nom+1))
  else
    nom=$((nom+2))
  fi
done

echo 'Cisco IP 89'
a="-tt -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.89"
  { sleep 2 ; eval $co ; sleep 1 ; eval $route ; sleep 1 ; eval $routeway ; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.$nom 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; echo "write" ; sleep 1 ; echo "y"; sleep 5 ; eval $x ; } | ssh $a




