#!/bin/bash

{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.61 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.1
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.62 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.6
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.63 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.73
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.64 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.74
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.66 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.78
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.67 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.79
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.68 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.80
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.69 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.82
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.70 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.83
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.71 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.84
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.72 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.85
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.73 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.86
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.74 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.89

echo ' '
echo 'ELTEX'
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.78 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.10
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.79 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.8
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.80 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.9
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.81 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.26
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.82 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.27
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.83 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.28
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.84 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.2
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.85 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.7

echo ' '
echo 'HUAWEI'
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.86 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.21
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.87 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.22
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.88 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.23
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.89 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.24
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.91 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.25
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.92 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.1.3
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.93 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.11
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.94 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.12
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.95 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.3
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.96 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.4
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.97 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.5
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.98 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.6
{ sleep 2; eval $b; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.99 255.255.255.0" ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; sleep 1 ; eval $q ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.1

echo ' '
echo 'SNR'
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.100 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.13
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.101 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.14
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.102 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.15
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.103 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.16
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.104 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.17
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.105 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.18
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.106 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.3
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.107 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.4
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.108 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.5
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.109 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.6
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.110 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.7
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.111 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.8
{ sleep 2; eval $a; sleep 1 ; eval $v ; sleep 1 ; echo "ip address 172.16.1.112 255.255.255.0" ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; sleep 1 ; eval $x ; } | ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.9

/usr/bin/expect<<EOF
spawn ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.20
expect "password:"
send "Angel1@$\n"
expect "SW-OPTIC1#"
send "show clock\n"
expect "SW-OPTIC1#"
send "exit\n"
EOF
/usr/bin/expect<<EOF
spawn ssh -tt -i /mnt/d/SSH/switches_openssh -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.25
expect "password:"
send "Angel1@$\n"
expect "SW-OPTIC1#"
send "show clock\n"
expect "SW-OPTIC1#"
send "exit\n"
EOF


#sleep 3
#echo "show clock"
#sleep 3
#echo 'exit'