#!/bin/bash
son=2
echo 'CISCO'
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.1
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.6
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.73
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.74
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.78
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.79
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.80
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.82
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.83
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.84
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.85
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.86
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-ctr -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.89

echo ' '
echo 'ELTEX'
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.10
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.8
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.9
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.26
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.27
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.28
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.2
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -c aes256-cbc -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.4.7

echo ' '
echo 'HUAWEI'
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.21
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.22
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.23
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.24
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.25
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.1.3
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.11
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.3.12
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.3
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.4
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.5
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.6
{ sleep 13; echo "display clock"; sleep 1; echo "quit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1 admin@172.16.4.1

echo ' '
echo 'SNR'
{{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.13
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.14
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.15
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.16
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.17
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.18
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.3
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.4
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.5
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.6
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.7
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.8
{ sleep $son; echo "show clock"; sleep 1; echo "exit" ; } | ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.3.9
/usr/bin/expect<<EOF
spawn ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.20
expect "password:"
send "Angel1@$\n"
expect "SW-OPTIC1#"
send "show clock\n"
expect "SW-OPTIC1#"
send "exit\n"
EOF
/usr/bin/expect<<EOF
spawn ssh -tt -o PubkeyAcceptedKeyTypes=+ssh-rsa -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group-exchange-sha1  admin@172.16.1.25
expect "password:"
send "Angel1@$\n"
expect "SW-OPTIC1#"
send "show clock\n"
expect "SW-OPTIC1#"
send "exit\n"
EOF


#sleep 3
#echo "show clock"
#sleep 3
#echo 'exit'